<template>
  <div class="about pa-6">
    <h1>About Viewtify todo</h1>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi et, laudantium necessitatibus non impedit cum! Magnam ipsum molestias iste excepturi? Tempore, consectetur rerum quo perspiciatis est quisquam dolores mollitia atque illo! Neque atque quis vero aperiam, corporis eum et dolores minus, facilis labore maxime libero illum suscipit quo eaque. Optio, laboriosam, praesentium perspiciatis assumenda delectus veritatis quam a culpa maiores magnam velit aliquam officiis enim sequi, voluptatibus quia qui ipsum nam ut amet rem quo voluptates provident nobis. Nobis nulla magni harum suscipit necessitatibus iste voluptatibus, tempora similique ullam id culpa voluptas asperiores velit, odio doloremque sint at. Ad, neque!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi et, laudantium necessitatibus non impedit cum! Magnam ipsum molestias iste excepturi? Tempore, consectetur rerum quo perspiciatis est quisquam dolores mollitia atque illo! Neque atque quis vero aperiam, corporis eum et dolores minus, facilis labore maxime libero illum suscipit quo eaque. Optio, laboriosam, praesentium perspiciatis assumenda delectus veritatis quam a culpa maiores magnam velit aliquam officiis enim sequi, voluptatibus quia qui ipsum nam ut amet rem quo voluptates provident nobis. Nobis nulla magni harum suscipit necessitatibus iste voluptatibus, tempora similique ullam id culpa voluptas asperiores velit, odio doloremque sint at. Ad, neque!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi et, laudantium necessitatibus non impedit cum! Magnam ipsum molestias iste excepturi? Tempore, consectetur rerum quo perspiciatis est quisquam dolores mollitia atque illo! Neque atque quis vero aperiam, corporis eum et dolores minus, facilis labore maxime libero illum suscipit quo eaque. Optio, laboriosam, praesentium perspiciatis assumenda delectus veritatis quam a culpa maiores magnam velit aliquam officiis enim sequi, voluptatibus quia qui ipsum nam ut amet rem quo voluptates provident nobis. Nobis nulla magni harum suscipit necessitatibus iste voluptatibus, tempora similique ullam id culpa voluptas asperiores velit, odio doloremque sint at. Ad, neque!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi et, laudantium necessitatibus non impedit cum! Magnam ipsum molestias iste excepturi? Tempore, consectetur rerum quo perspiciatis est quisquam dolores mollitia atque illo! Neque atque quis vero aperiam, corporis eum et dolores minus, facilis labore maxime libero illum suscipit quo eaque. Optio, laboriosam, praesentium perspiciatis assumenda delectus veritatis quam a culpa maiores magnam velit aliquam officiis enim sequi, voluptatibus quia qui ipsum nam ut amet rem quo voluptates provident nobis. Nobis nulla magni harum suscipit necessitatibus iste voluptatibus, tempora similique ullam id culpa voluptas asperiores velit, odio doloremque sint at. Ad, neque!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi et, laudantium necessitatibus non impedit cum! Magnam ipsum molestias iste excepturi? Tempore, consectetur rerum quo perspiciatis est quisquam dolores mollitia atque illo! Neque atque quis vero aperiam, corporis eum et dolores minus, facilis labore maxime libero illum suscipit quo eaque. Optio, laboriosam, praesentium perspiciatis assumenda delectus veritatis quam a culpa maiores magnam velit aliquam officiis enim sequi, voluptatibus quia qui ipsum nam ut amet rem quo voluptates provident nobis. Nobis nulla magni harum suscipit necessitatibus iste voluptatibus, tempora similique ullam id culpa voluptas asperiores velit, odio doloremque sint at. Ad, neque!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi et, laudantium necessitatibus non impedit cum! Magnam ipsum molestias iste excepturi? Tempore, consectetur rerum quo perspiciatis est quisquam dolores mollitia atque illo! Neque atque quis vero aperiam, corporis eum et dolores minus, facilis labore maxime libero illum suscipit quo eaque. Optio, laboriosam, praesentium perspiciatis assumenda delectus veritatis quam a culpa maiores magnam velit aliquam officiis enim sequi, voluptatibus quia qui ipsum nam ut amet rem quo voluptates provident nobis. Nobis nulla magni harum suscipit necessitatibus iste voluptatibus, tempora similique ullam id culpa voluptas asperiores velit, odio doloremque sint at. Ad, neque!</p>
  </div>
</template>
